### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by inushima** [oggysy/TimeDifference#1]
細かい点で恐縮ですが、ボタン名についてアプリだとクリックよりは、「タップ」とするほうが多いです。

**Comment by inushima** [comment]
トップレベルのStackView直下のViewはなくても問題ないかと思います。

StackViewもViewですので、StackView直下にStackViewを配置できます。

![スクリーンショット 2023-01-18 16 34 49](https://user-images.githubusercontent.com/8144028/213111040-f66ca004-5a12-435c-b011-db557270c94c.jpg)

**Comment by inushima** [comment]
https://github.com/oggysy/TimeDifference/blob/main/TimeDifference/ViewController.swift#L31

強制アンラップは極力使わないほうが望ましいです。
この場合はguardでunwrapできます。

```
        guard let pressedButtonTimeData =  pressedButtonTimeData else { return } 
        differentTimeData = Int(currentTimeData.timeIntervalSince(pressedButtonTimeData))
        differentTime.text = String(differentTimeData)
```

**Comment by inushima** [comment]
https://github.com/oggysy/TimeDifference/blob/main/TimeDifference/ViewController.swift#L17

updateTimerメソッド内でのみ参照されているので、インスタンス変数にしなくても大丈夫そうです。

**Comment by inushima** [comment]
UIKitの変数については、何の部品か分かる用に変数名にUI以降のクラス名をつけることが一般的です。

```
    @IBOutlet weak var currentTimeLabel: UILabel!
    @IBOutlet weak var pressedButtonTimeLabel: UILabel!
    @IBOutlet weak var differentTimeLabel: UILabel!
```

**Comment by inushima** [comment]
https://github.com/oggysy/TimeDifference/blob/main/TimeDifference/ViewController.swift#L15

Data -> Dateが適切かと思います。

```
    var currentTimeDate = Date()
    var pressedButtonTimeDate:Date? = nil
```

**Comment by inushima** [comment]
https://github.com/oggysy/TimeDifference/blob/main/TimeDifference/ViewController.swift#L25

インデントがずれているようです。

**Comment by oggysy** [comment]
6点修正しました。
・ボタン名をクリック→タップ
・強制アンラップ→guardに変更
・differentTimeDate変数をメソッド内で定義
・UIKitの変数名の変更
・変数名のDataをDateに修正
・インデントの修正
ご確認をお願いいたします。
https://github.com/oggysy/TimeDifference/commits/main

**Comment by inushima** [comment]
LGTM!
